# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180530_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='short_url',
            field=models.CharField(max_length=6),
        ),
    ]
